# Generated by Django 5.1.1 on 2025-02-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
    ]
